ALTER TABLE `Sucursal`.`Clientes` 
ADD COLUMN `Edad` TINYINT(3) NOT NULL AFTER `idCuenta`,
ADD COLUMN `Genero` VARCHAR(10) NOT NULL AFTER `Edad`;

ALTER TABLE `Sucursal`.`Clientes` 
CHANGE COLUMN `Edad` `Edad` TINYINT(3) NOT NULL AFTER `Apellido`,
CHANGE COLUMN `Genero` `Genero` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `Edad`;

UPDATE `Sucursal`.`Clientes` SET `Edad`='80', `Genero`='Masc' WHERE `idCliente`='1';
UPDATE `Sucursal`.`Clientes` SET `Edad`='18', `Genero`='Masc' WHERE `idCliente`='2';
UPDATE `Sucursal`.`Clientes` SET `Edad`='26', `Genero`='Fem' WHERE `idCliente`='3';
UPDATE `Sucursal`.`Clientes` SET `Edad`='36', `Genero`='Fem' WHERE `idCliente`='4';
UPDATE `Sucursal`.`Clientes` SET `Edad`='66', `Genero`='Masc' WHERE `idCliente`='5';
UPDATE `Sucursal`.`Clientes` SET `Edad`='22', `Genero`='Fem' WHERE `idCliente`='6';
UPDATE `Sucursal`.`Clientes` SET `Edad`='68', `Genero`='Masc' WHERE `idCliente`='7';
UPDATE `Sucursal`.`Clientes` SET `Edad`='20', `Genero`='Masc' WHERE `idCliente`='8';
UPDATE `Sucursal`.`Clientes` SET `Edad`='25', `Genero`='Masc' WHERE `idCliente`='9';
UPDATE `Sucursal`.`Clientes` SET `Edad`='63', `Genero`='Fem' WHERE `idCliente`='10';
UPDATE `Sucursal`.`Clientes` SET `Edad`='44', `Genero`='Fem' WHERE `idCliente`='11';
UPDATE `Sucursal`.`Clientes` SET `Edad`='45', `Genero`='Masc' WHERE `idCliente`='12';
UPDATE `Sucursal`.`Clientes` SET `Edad`='68', `Genero`='Fem' WHERE `idCliente`='13';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Masc' WHERE `idCliente`='14';
UPDATE `Sucursal`.`Clientes` SET `Edad`='32', `Genero`='Masc' WHERE `idCliente`='15';
UPDATE `Sucursal`.`Clientes` SET `Edad`='35', `Genero`='Masc' WHERE `idCliente`='16';
UPDATE `Sucursal`.`Clientes` SET `Edad`='22', `Genero`='Fem' WHERE `idCliente`='17';
UPDATE `Sucursal`.`Clientes` SET `Edad`='29', `Genero`='Masc' WHERE `idCliente`='18';
UPDATE `Sucursal`.`Clientes` SET `Edad`='27', `Genero`='Masc' WHERE `idCliente`='19';
UPDATE `Sucursal`.`Clientes` SET `Edad`='34', `Genero`='Fem' WHERE `idCliente`='20';
UPDATE `Sucursal`.`Clientes` SET `Edad`='27', `Genero`='Masc' WHERE `idCliente`='21';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Masc' WHERE `idCliente`='22';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Masc' WHERE `idCliente`='23';
UPDATE `Sucursal`.`Clientes` SET `Edad`='63', `Genero`='Fem' WHERE `idCliente`='24';
UPDATE `Sucursal`.`Clientes` SET `Edad`='65', `Genero`='Fem' WHERE `idCliente`='25';
UPDATE `Sucursal`.`Clientes` SET `Edad`='65', `Genero`='Fem' WHERE `idCliente`='26';
UPDATE `Sucursal`.`Clientes` SET `Edad`='45', `Genero`='Masc' WHERE `idCliente`='27';
UPDATE `Sucursal`.`Clientes` SET `Edad`='25', `Genero`='Fem' WHERE `idCliente`='28';
UPDATE `Sucursal`.`Clientes` SET `Edad`='19', `Genero`='Masc' WHERE `idCliente`='29';
UPDATE `Sucursal`.`Clientes` SET `Edad`='26', `Genero`='Fem' WHERE `idCliente`='30';
UPDATE `Sucursal`.`Clientes` SET `Edad`='56', `Genero`='Masc' WHERE `idCliente`='31';
UPDATE `Sucursal`.`Clientes` SET `Edad`='85', `Genero`='Masc' WHERE `idCliente`='32';
UPDATE `Sucursal`.`Clientes` SET `Edad`='64', `Genero`='Masc' WHERE `idCliente`='33';
UPDATE `Sucursal`.`Clientes` SET `Edad`='32', `Genero`='Masc' WHERE `idCliente`='34';
UPDATE `Sucursal`.`Clientes` SET `Edad`='31', `Genero`='Masc' WHERE `idCliente`='35';
UPDATE `Sucursal`.`Clientes` SET `Edad`='36', `Genero`='Masc' WHERE `idCliente`='36';
UPDATE `Sucursal`.`Clientes` SET `Edad`='45', `Genero`='Masc' WHERE `idCliente`='37';
UPDATE `Sucursal`.`Clientes` SET `Edad`='40', `Genero`='Fem' WHERE `idCliente`='38';
UPDATE `Sucursal`.`Clientes` SET `Edad`='60', `Genero`='Masc' WHERE `idCliente`='39';
UPDATE `Sucursal`.`Clientes` SET `Edad`='30', `Genero`='Fem' WHERE `idCliente`='40';
UPDATE `Sucursal`.`Clientes` SET `Edad`='41', `Genero`='Fem' WHERE `idCliente`='41';
UPDATE `Sucursal`.`Clientes` SET `Edad`='38', `Genero`='Masc' WHERE `idCliente`='42';
UPDATE `Sucursal`.`Clientes` SET `Edad`='35', `Genero`='Masc' WHERE `idCliente`='43';
UPDATE `Sucursal`.`Clientes` SET `Edad`='31', `Genero`='Masc' WHERE `idCliente`='44';
UPDATE `Sucursal`.`Clientes` SET `Edad`='28', `Genero`='Fem' WHERE `idCliente`='45';
UPDATE `Sucursal`.`Clientes` SET `Edad`='59', `Genero`='Fem' WHERE `idCliente`='46';
UPDATE `Sucursal`.`Clientes` SET `Edad`='63', `Genero`='Masc' WHERE `idCliente`='47';
UPDATE `Sucursal`.`Clientes` SET `Edad`='32', `Genero`='Masc' WHERE `idCliente`='48';
UPDATE `Sucursal`.`Clientes` SET `Edad`='56', `Genero`='Masc' WHERE `idCliente`='49';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Masc' WHERE `idCliente`='50';
UPDATE `Sucursal`.`Clientes` SET `Edad`='19', `Genero`='Fem' WHERE `idCliente`='51';
UPDATE `Sucursal`.`Clientes` SET `Edad`='28', `Genero`='Masc' WHERE `idCliente`='52';
UPDATE `Sucursal`.`Clientes` SET `Edad`='24', `Genero`='Masc' WHERE `idCliente`='53';
UPDATE `Sucursal`.`Clientes` SET `Edad`='26', `Genero`='Masc' WHERE `idCliente`='54';
UPDATE `Sucursal`.`Clientes` SET `Edad`='23', `Genero`='Masc' WHERE `idCliente`='55';
UPDATE `Sucursal`.`Clientes` SET `Edad`='22', `Genero`='Fem' WHERE `idCliente`='56';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Masc' WHERE `idCliente`='57';
UPDATE `Sucursal`.`Clientes` SET `Edad`='85', `Genero`='Masc' WHERE `idCliente`='58';
UPDATE `Sucursal`.`Clientes` SET `Edad`='80', `Genero`='Fem' WHERE `idCliente`='59';
UPDATE `Sucursal`.`Clientes` SET `Edad`='83', `Genero`='Masc' WHERE `idCliente`='60';
UPDATE `Sucursal`.`Clientes` SET `Edad`='64', `Genero`='Masc' WHERE `idCliente`='61';
UPDATE `Sucursal`.`Clientes` SET `Edad`='50', `Genero`='Masc' WHERE `idCliente`='62';
UPDATE `Sucursal`.`Clientes` SET `Edad`='47', `Genero`='Fem' WHERE `idCliente`='63';
UPDATE `Sucursal`.`Clientes` SET `Edad`='56', `Genero`='Masc' WHERE `idCliente`='64';
UPDATE `Sucursal`.`Clientes` SET `Edad`='23', `Genero`='Fem' WHERE `idCliente`='65';
UPDATE `Sucursal`.`Clientes` SET `Edad`='28', `Genero`='Masc' WHERE `idCliente`='66';
UPDATE `Sucursal`.`Clientes` SET `Edad`='27', `Genero`='Masc' WHERE `idCliente`='67';
UPDATE `Sucursal`.`Clientes` SET `Edad`='26', `Genero`='Fem' WHERE `idCliente`='68';
UPDATE `Sucursal`.`Clientes` SET `Edad`='38', `Genero`='Otro' WHERE `idCliente`='69';
UPDATE `Sucursal`.`Clientes` SET `Edad`='32', `Genero`='Otro' WHERE `idCliente`='70';
UPDATE `Sucursal`.`Clientes` SET `Edad`='38', `Genero`='Masc' WHERE `idCliente`='71';
UPDATE `Sucursal`.`Clientes` SET `Edad`='33', `Genero`='Masc' WHERE `idCliente`='72';
UPDATE `Sucursal`.`Clientes` SET `Edad`='33', `Genero`='Masc' WHERE `idCliente`='73';
UPDATE `Sucursal`.`Clientes` SET `Edad`='44', `Genero`='Masc' WHERE `idCliente`='74';
UPDATE `Sucursal`.`Clientes` SET `Edad`='55', `Genero`='Otro' WHERE `idCliente`='75';
UPDATE `Sucursal`.`Clientes` SET `Edad`='61', `Genero`='Masc' WHERE `idCliente`='76';
UPDATE `Sucursal`.`Clientes` SET `Edad`='28', `Genero`='Masc' WHERE `idCliente`='77';
UPDATE `Sucursal`.`Clientes` SET `Edad`='71', `Genero`='Masc' WHERE `idCliente`='78';
UPDATE `Sucursal`.`Clientes` SET `Edad`='32', `Genero`='Masc' WHERE `idCliente`='79';
UPDATE `Sucursal`.`Clientes` SET `Edad`='56', `Genero`='Fem' WHERE `idCliente`='80';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Masc' WHERE `idCliente`='81';
UPDATE `Sucursal`.`Clientes` SET `Edad`='65', `Genero`='Otro' WHERE `idCliente`='82';
UPDATE `Sucursal`.`Clientes` SET `Edad`='66', `Genero`='Masc' WHERE `idCliente`='83';
UPDATE `Sucursal`.`Clientes` SET `Edad`='33', `Genero`='Fem' WHERE `idCliente`='84';
UPDATE `Sucursal`.`Clientes` SET `Edad`='54', `Genero`='Fem' WHERE `idCliente`='85';
UPDATE `Sucursal`.`Clientes` SET `Edad`='32', `Genero`='Masc' WHERE `idCliente`='86';
UPDATE `Sucursal`.`Clientes` SET `Edad`='30', `Genero`='Masc' WHERE `idCliente`='87';
UPDATE `Sucursal`.`Clientes` SET `Edad`='50', `Genero`='Masc' WHERE `idCliente`='88';
UPDATE `Sucursal`.`Clientes` SET `Edad`='20', `Genero`='Masc' WHERE `idCliente`='89';
UPDATE `Sucursal`.`Clientes` SET `Edad`='21', `Genero`='Masc' WHERE `idCliente`='90';
UPDATE `Sucursal`.`Clientes` SET `Edad`='22', `Genero`='Fem' WHERE `idCliente`='91';
UPDATE `Sucursal`.`Clientes` SET `Edad`='33', `Genero`='Fem' WHERE `idCliente`='92';
UPDATE `Sucursal`.`Clientes` SET `Edad`='29', `Genero`='Fem' WHERE `idCliente`='93';
UPDATE `Sucursal`.`Clientes` SET `Edad`='43', `Genero`='Fem' WHERE `idCliente`='94';
UPDATE `Sucursal`.`Clientes` SET `Edad`='45', `Genero`='Masc' WHERE `idCliente`='95';
UPDATE `Sucursal`.`Clientes` SET `Edad`='48', `Genero`='Fem' WHERE `idCliente`='96';
UPDATE `Sucursal`.`Clientes` SET `Edad`='49', `Genero`='Fem' WHERE `idCliente`='97';
UPDATE `Sucursal`.`Clientes` SET `Edad`='50', `Genero`='Masc' WHERE `idCliente`='98';
UPDATE `Sucursal`.`Clientes` SET `Edad`='18', `Genero`='Fem' WHERE `idCliente`='99';
UPDATE `Sucursal`.`Clientes` SET `Edad`='19', `Genero`='Fem' WHERE `idCliente`='100';

ALTER TABLE `Sucursal`.`Clientes` 
CHANGE COLUMN `Nombre` `Nombre` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL ;
