
ALTER TABLE `Sucursal`.`Ordenes` 
DROP FOREIGN KEY `fk_Ordenes_Clientes1`;
ALTER TABLE `Sucursal`.`Ordenes` 
DROP COLUMN `idCliente`,
DROP INDEX `fk_Ordenes_Clientes1_idx` ;

ALTER TABLE `Sucursal`.`Clientes` 
CHANGE COLUMN `idCliente` `idCliente` INT(11) NOT NULL AUTO_INCREMENT ;


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `Sucursal`.`Ordenes` 
ADD COLUMN `idCliente` INT(11) NOT NULL AFTER `Fecha`,
ADD INDEX `fk_Ordenes_Clientes1_idx` (`idCliente` ASC);

ALTER TABLE `Sucursal`.`Ordenes` 
ADD CONSTRAINT `fk_Ordenes_Clientes1`
  FOREIGN KEY (`idCliente`)
  REFERENCES `Sucursal`.`Clientes` (`idCliente`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE `Sucursal`.`Clientes` 
ADD UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC);
